INCLUDE_PATH = "../../../Include/"

insertionSort:
	g++ -o Insertion_Sort Insertion_Sort.cpp -I ${INCLUDE_PATH}

radixSort:
	g++ -o Radix_Sort Radix_Sort.cpp -I ${INCLUDE_PATH}

heapSort:
	g++ -o Heap_Sort Heap_Sort.cpp -I ${INCLUDE_PATH}

mergeSort:
	g++ -o Merge_Sort Merge_Sort.cpp -I ${INCLUDE_PATH}

quickSort:
	g++ -o Quick_Sort Quick_Sort.cpp -I ${INCLUDE_PATH}

clear:
	-rm -rf *_Sort